# Generated by Django 5.0.3 on 2024-03-05 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARTIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARTIST_NAME', models.CharField(max_length=255)),
                ('ARTIST_TYPE', models.CharField(max_length=255)),
                ('ARTIST_IMAGE', models.ImageField(upload_to='artistimg')),
                ('ARTIST_DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAT_NAME', models.CharField(max_length=50)),
                ('CAT_IMAGE', models.ImageField(upload_to='catphotos')),
            ],
        ),
        migrations.CreateModel(
            name='REGISTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=255)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PASSWORD', models.CharField(max_length=255)),
                ('PHONE', models.BigIntegerField()),
                ('DOB', models.DateField()),
                ('DP', models.ImageField(upload_to='userimg')),
                ('GENDER', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MUSIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SONG_TITLE', models.CharField(max_length=255)),
                ('DURATION', models.TimeField()),
                ('TIMESTAMP', models.DateTimeField(auto_now=True)),
                ('SONG_YEAR', models.CharField(max_length=4)),
                ('SONG_IMAGE', models.ImageField(upload_to='songimage')),
                ('ARTIST_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artist')),
                ('CAT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='PLAYLIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.BooleanField()),
                ('SONG_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.music')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
    ]
