# Generated by Django 5.0.3 on 2024-03-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='DURATION',
            field=models.CharField(max_length=255),
        ),
    ]
