# Generated by Django 5.0.3 on 2024-03-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_music_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='STATUS',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=255),
        ),
    ]
