# Generated by Django 5.0.3 on 2024-03-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_music_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='PLAYLIST_NAME',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
