# Generated by Django 5.0.3 on 2024-03-09 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_playlist_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='SONG_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.music'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='STATUS',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=255, null=True),
        ),
    ]
